#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__ . '/bootstrap/app.php';
$container = $app->getContainer();

$commands = require __DIR__ . '/config/commands.php';

$application = new Application('Art', '1.0');

$application->addCommands(array_map(fn($command) => $container->get($command), $commands));

$application->run();
