#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Application;

$app = require __DIR__ . '/bootstrap/app.php';
$container = $app->getContainer();

$commands = require CONFIG_PATH . '/commands.php';

$application = new Application('Lumi', '1.0');

$application->addCommands(array_map(fn($command) => $container->get($command), $commands));

$application->run();
